import type { Metadata } from "next";
import "./globals.css";
import { CombinedProvider } from "@/providers/CombinedProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<body className={``}>
				<CombinedProvider>{children}</CombinedProvider>
			</body>
		</html>
	);
}
