export enum Icons {
	LANGUAGE = 'LANGUAGE',
	HOMEFILL = 'HOMEFILL',
	SETTINGFILL = 'SETTINGFILL',
	CATEGORYFILL = 'CATEGORYFILL',
	MOVIEFILL = 'MOVIEFILL',
	TVFILL = 'TVFILL',
	ARROWLEFT = 'ARROWLEFT',
	ARROWRIGHT = 'ARROWRIGHT',
	LOGO = 'LOGO',
}
